### ISSUE TITLE
Could not resolve to a node with the global id of ''

### ISSUE THREAD

**Issue by retorquere** [suzuki-shunsuke/ghproj#110]
When running

```
GITHUB_TOKEN=ghp_... ghproj add
```

I'm getting

```
error=handle an entry: add an item to a project: add an issue or a pull request to a GitHub Project by GitHub GraphQL API (addProjectNextItem): Could not resolve to a node with the global id of '' program=ghproj version=0.1.2
```

my ghproj.yaml is

```
---
# ghproj https://github.com/suzuki-shunsuke/ghproj
entries:
  - user: retorquere
    query: |
      is:open
      is:public
      archived:false
    project_number: 5
    types:
      - issue
      - pr
    repositories:
      - zotero-better-bibtex
    excluded_repositories:
      - foo
```
