### ISSUE TITLE
Support setting variables passed to expressions

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghproj#31]
```yaml
expr: |
  Item.Title in Vars.titles
vars:
  titles:
    - Dependency Dashboard
    - screen shot
```
