### ISSUE TITLE
Support updating issues and pull requests

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghproj#35]
```yaml
  - expr: |
      (Item.Title == "screen shot")
    labels:
      - screen shot
```
