### ISSUE TITLE
Support archiving items when the number of items reaches the limitation

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghproj#37]
```yaml
archive:
  expr: |
      Item.Repo.IsArchived
    project_id: PVT_kwHOAMtMJ84AQCf4
```
